# Builds and publishes the project to Docker Hub and GitHub Container Registry
name: deploy-docker-from-repository-dispatch

# Triggered when we receive a `build_deploy` dispatch
on:
  repository_dispatch:
    types:
      - build_deploy

jobs:
  deploy-docker:
    name: Deploy To Docker Hub + GitHub Container Registry
    runs-on: ubuntu-latest

    # Packages write permission to allow publishing GitHub package
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
          docker_hub_token: ${{ secrets.DOCKER_TOKEN }}
          ghcr_token: ${{ github.token }}
          version: ${{ github.event.client_payload.version }}
