# Deploys Docker images from a manual trigger
name: deploy-docker-manually

# Triggered manually
on:
  workflow_dispatch:

jobs:
  deploy-docker:
    name: Deploy To Docker Hub + GitHub Container Registry
    runs-on: ubuntu-latest

    # Packages write permission to allow publishing GitHub package
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2

      - name: Get Next Version
        id: getnextversion
        uses: ./.github/actions/get-version

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
          docker_hub_token: ${{ secrets.DOCKER_TOKEN }}
          ghcr_token: ${{ github.token }}
          version: ${{ steps.getnextversion.outputs.version }}
