# Releases the project to GitHub
name: release

# Triggered only when a new version tag is pushed to main, format "x.y.z"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Release to GitHub
    runs-on: ubuntu-latest

    # Write permissions to allow creating the release
    permissions:
      contents: write # It'd be nice if we could restrict this to just releases

    steps:
      - name: Pull GHCR Images
        # Pulls images for each platform for the tag version
        run: |
          docker pull --platform=linux/amd64 ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }}
          docker pull --platform=linux/arm64 ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }}
          docker pull --platform=linux/arm/v7 ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }}

      - name: Create Tarballs
        # Saves the images to separate gzipped tarballs
        run: |
          mkdir output
          docker image save \
          --platform=linux/amd64 \
          ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }} | \
          gzip > ./output/twitch-channel-points-miner-linux-amd64.tar.gz
          docker image save \
          --platform=linux/arm64 \
          ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }} | \
          gzip > ./output/twitch-channel-points-miner-linux-arm64.tar.gz
          docker image save \
          --platform=linux/arm/v7 \
          ghcr.io/mpforce1/twitch-channel-points-miner:${{ github.ref_name }} | \
          gzip > ./output/twitch-channel-points-miner-linux-arm-v7.tar.gz

      - name: Create GitHub Release
        # Creates a draft release for manual review
        uses: softprops/action-gh-release@v2.5.0
        with:
          generate_release_notes: true
          files: ./output/**/*
          draft: true
